### ISSUE TITLE
issues in my webpage link

### ISSUE THREAD

**Issue by DamienAllonsius** [Naereen/me#23]
Hey Lilian, in case you want to avoid getting a 404 error page when clicking on my name in your section https://github.com/Naereen/me#friends-who-got-inspired, you can change the target url to https://damienallonsius.github.io/ ;)
cheers!

**Comment by Naereen** [comment]
Hi there @DamienAllonsius,
Thanks for the notice, I changed the README on Naereen/me to use your link.
Regards 😘
Lilian
